spring.application.name=reservation_be

server.address=0.0.0.0

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/reservation?serverTimezone=UTC&characterEncoding=UTF-8
#spring.datasource.url=jdbc:mysql://walab.handong.edu:3306/naimkim?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Okok1186!

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.mvc.dispatch-options-request=true

spring.web.cors.allowed-origins=http://localhost:3000

# Set database type to MySQL
spring.jpa.database=mysql

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect